common:
  model_path: '../VideoPose3D/common/model.py'
  model_name: 'TemporalModel'
  ckpt_path: '../VideoPose3D/checkpoint/arc_33_ch_1024_epoch_80.bin'
  input_shape: [1, 9, 17, 2]
model:
  num_joints_in: 17
  in_features: 2
  num_joints_out: 17
  filter_widths: [3,3]
  causal: False
  dropout: 0.25
  channels: 1024