common:
  device: 'cuda'
  model_path: '../VideoPose3D/common/model.py'
  model_name: 'TemporalModelOptimized1f'
  ckpt_path: '../VideoPose3D/checkpoint/pretrained_h36m_cpn.bin'
  input_shape: [2, 3561, 17, 2]
model:
  num_joints_in: 17
  in_features: 2
  num_joints_out: 17
  filter_widths: [3,3, 3, 3, 3]
  causal: False
  dropout: 0.25
  channels: 1024